# Generated by Django 5.2.3 on 2025-06-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
