# Generated by Django 5.2.3 on 2025-06-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todomodel_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='mwmo',
            new_name='memo',
        ),
    ]
