# Generated by Django 5.2.3 on 2025-06-21 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_mwmo_todomodel_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='duedate',
            field=models.DateField(default=datetime.date(2025, 6, 21)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('danger', 'high'), ('warning', 'normal'), ('primary', 'low')], default=datetime.date(2025, 6, 21), max_length=50),
            preserve_default=False,
        ),
    ]
